# Generated by Django 5.0.2 on 2025-11-12 12:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('ename', models.CharField(db_column='eName', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Class (Lớp)',
                'db_table': 'class',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Tài liệu',
                'db_table': 'document',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('family_id', models.AutoField(primary_key=True, serialize=False)),
                ('ename', models.CharField(db_column='eName', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Family (Họ)',
                'db_table': 'family',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genus',
            fields=[
                ('genus_id', models.AutoField(primary_key=True, serialize=False)),
                ('ename', models.CharField(db_column='eName', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Genus (Chi)',
                'db_table': 'genus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InsectsBbox',
            fields=[
                ('box_id', models.AutoField(primary_key=True, serialize=False)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Nhãn',
                'db_table': 'insects_bbox',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InsectsImage',
            fields=[
                ('img_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('desc', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name_plural': 'Hình ảnh',
                'db_table': 'insects_image_detect_15k',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kingdom',
            fields=[
                ('kingdom_id', models.AutoField(primary_key=True, serialize=False)),
                ('ename', models.CharField(db_column='eName', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Kingdom (Giới)',
                'db_table': 'kingdom',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('ename', models.CharField(db_column='eName', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Order (Bộ)',
                'db_table': 'order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Phylum',
            fields=[
                ('phylum_id', models.AutoField(primary_key=True, serialize=False)),
                ('ename', models.CharField(db_column='eName', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Phylum (Ngành)',
                'db_table': 'phylum',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('ename', models.CharField(db_column='eName', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('species_name', models.CharField(max_length=200)),
                ('eng_name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('morphologic_feature', models.TextField()),
                ('distribution', models.TextField()),
                ('characteristic', models.TextField()),
                ('behavior', models.TextField()),
                ('protection_method', models.TextField()),
                ('thumbnail', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=8, null=True)),
                ('verification_count', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RequestDesc',
            fields=[
                ('request_desc_id', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.TextField()),
                ('status', models.CharField(blank=True, max_length=8, null=True)),
                ('verification_count', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'request_desc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('insects_id', models.AutoField(primary_key=True, serialize=False)),
                ('ename', models.CharField(db_column='eName', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('species_name', models.CharField(max_length=200)),
                ('eng_name', models.CharField(max_length=100)),
                ('vi_name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('morphologic_feature', models.TextField()),
                ('distribution', models.TextField()),
                ('characteristic', models.TextField()),
                ('behavior', models.TextField()),
                ('protection_method', models.TextField()),
                ('thumbnail', models.CharField(blank=True, max_length=255, null=True)),
                ('is_new', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Species (Loài)',
                'db_table': 'species',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('desc', 'Mô tả ảnh'), ('image', 'Ảnh côn trùng mới'), ('species', 'Đề xuất loài mới')], max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'verification_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InsectsCrawler',
            fields=[
                ('crawler_id', models.AutoField(primary_key=True, serialize=False)),
                ('img_url', models.URLField(db_column='img_url', null=True)),
                ('img_id', models.CharField(db_column='img_id', max_length=50, null=True)),
                ('crawl_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('processing', 'Processing')], default='processing', max_length=20)),
                ('insects_id', models.ForeignKey(db_column='insects_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='insects.species')),
                ('user_id', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'insects_crawler',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestImage',
            fields=[
                ('request_img_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(db_column='url', null=True)),
                ('request_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(blank=True, max_length=8, null=True)),
                ('verification_count', models.IntegerField(blank=True, null=True)),
                ('insects_id', models.ForeignKey(db_column='insects_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='insects.species')),
                ('user_id', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'request_image',
            },
        ),
    ]
