# Generated by Django 5.0.2 on 2025-11-12 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insects', '0001_initial'),
    ]

    operations = [
        
    ]
