# Generated by Django 5.0.2 on 2026-01-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insects', '0002_add_created_at_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestimage',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
