# Generated by Django 5.0.2 on 2026-01-07 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insects', '0003_requestimage_desc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('scientific_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'crop',
            },
        ),
        migrations.CreateModel(
            name='AdministrativeRegion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('country', 'Quốc gia'), ('province', 'Tỉnh'), ('district', 'Huyện'), ('commune', 'Xã')], max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='insects.administrativeregion')),
            ],
            options={
                'db_table': 'administrative_region',
            },
        ),
        migrations.CreateModel(
            name='InsectCropDamage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('damage_level', models.CharField(choices=[('low', 'Nhẹ'), ('medium', 'Trung bình'), ('high', 'Nặng')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('expert_approved', 'Chuyên gia duyệt'), ('admin_approved', 'Admin duyệt'), ('rejected', 'Từ chối')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insects.crop')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insects.species')),
            ],
            options={
                'db_table': 'insect_crop_damage',
            },
        ),
        migrations.CreateModel(
            name='InsectDistribution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('observation_date', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('expert_approved', 'Chuyên gia duyệt'), ('admin_approved', 'Admin duyệt'), ('rejected', 'Từ chối')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insects.administrativeregion')),
                ('species', models.ForeignKey(db_column='insects_id', on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='insects.species')),
            ],
            options={
                'db_table': 'insect_distribution',
            },
        ),
        migrations.CreateModel(
            name='DistributionReviewLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('expert', 'Chuyên gia'), ('admin', 'Admin')], max_length=20)),
                ('action', models.CharField(choices=[('approve', 'Đồng ý'), ('reject', 'Từ chối')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to='insects.insectdistribution')),
            ],
            options={
                'db_table': 'distribution_review_log',
            },
        ),
    ]
