# Generated by Django 5.0.2 on 2026-01-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insects', '0004_crop_administrativeregion_insectcropdamage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='cultivation_area',
            field=models.TextField(blank=True, null=True, verbose_name='Vùng trồng phổ biến'),
        ),
        migrations.AddField(
            model_name='crop',
            name='economic_value',
            field=models.TextField(blank=True, null=True, verbose_name='Giá trị kinh tế'),
        ),
        migrations.AddField(
            model_name='crop',
            name='morphology',
            field=models.TextField(blank=True, null=True, verbose_name='Đặc điểm hình thái'),
        ),
    ]
