# Generated by Django 5.0.2 on 2026-01-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insects', '0005_crop_cultivation_area_crop_economic_value_and_more'),
    ]

    operations = [
       # migrations.AddField(
        #    model_name='insectdistribution',
        #    name='observation_image',
        #    field=models.ImageField(blank=True, null=True, upload_to='distribution_images/'),
       # ),
    ]
