# Generated by Django 5.0.2 on 2026-01-17 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insects', '0006_insectdistribution_observation_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionBoundingBox',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('confidence', models.FloatField(default=0)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('distribution', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='bboxes',
                    to='insects.insectdistribution'
                )),
            ],
            options={
                'db_table': 'distribution_bounding_box',
            },
        ),
    ]
